name: Deploy to On-Premises

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to On-Premises
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOST: ${{ secrets.KNOWN_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
          echo "$KNOWN_HOST" > ~/.ssh/known_hosts
          ssh -i key johndoe@118.240.154.3 -p 50022 "cd ~/team_project && git pull origin main && ./deploy.sh"
