name: Deploy to On-Premises

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

  steps:
    - uses: shimataro/ssh-key-action@v1
    - name: Install SSH key
      with: 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }} 
        config: |
              Host nic
                HostName 118.240.154.3
                Port 50022
                User johndoe
                IdentityFile ~/.ssh/id_rsa

    - name: run deploy script
      run: cd ~/team_project && git pull origin main && ./deploy.sh

    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Deploy to On-Premises
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #       KNOWN_HOST: ${{ secrets.KNOWN_HOST }}
    #     run: |
    #       mkdir -p ~/.ssh
    #       echo "$SSH_PRIVATE_KEY" > ~/.ssh/key && chmod 600 ~/.ssh/key
    #       echo "$KNOWN_HOST" > ~/.ssh/known_hosts
    #       ssh -i ~/.ssh/key johndoe@118.240.154.3 -p 50022 "cd ~/team_project && git pull origin main && ./deploy.sh"
