name: Deploy to On-Premises

on:
  push:
    branches:
      - main
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: run deploy script
        run: |
          ssh -o StrictHostKeyChecking=no johndoe@118.240.154.3 -p 50022 "cd ~/team_project && git pull origin main && ./deploy.sh"
